# Exercise 6: NumPy

In [12]:
import numpy as np

### NaN and infinity

NumPy (and other computer languages/libraries) have a special value called `NaN` ([Not a Number](https://en.wikipedia.org/wiki/NaN)).
NaN is the result of various arithmetic operations, e.g. 0/0, $-\infty + \infty$.

In NumPy, NaN is represented as `np.nan`.  NaN satisfies the following properties:

* Comparisons of NaN with a number x using one of the operators =, <, >, >=, and <= is always False.  Consequently, x != NaN is always True.

* Any arithmetic operation involving a NaN leads to a NaN 

Infinity is represented using `np.inf`, and negative infinity is `-np.inf`.

* Experiment with NaN and infinity and convince yourself that the results of the following operations make sense to you:

```Pytnon
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - 1
```

In [13]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - 1

nan

Now try the following:

In [14]:
0.3 == 3 * 0.1

False

The reason why the result is false is because floating point numbers cannot always be represented in binary. Therfore rounding errors occur making it so that the values will not match exactly to be True. 
*your explanation here*i

### Creating arrays

* Create a 3x3 matrix with integer values ranging from 0 to 8.  Do this by creating a one dimensional array and using the [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) function.

In [24]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

* Create the same 3x3 matrix and have the end result be a floating point array.

In [25]:
np.arange(0,9, dtype=float).reshape(3,3)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

* Create a vector of length 10 with random values between 0 and 1

In [ ]:
seed = 42
from numpy.random import default_rng
rng = default_rng(seed)  
rng.random(10)

array([0.77395605, 0.43887844, 0.85859792, 0.69736803, 0.09417735,
       0.97562235, 0.7611397 , 0.78606431, 0.12811363, 0.45038594])

* Create a 10x10 array with 1 on the border and 0 inside

In [36]:
arr = np.ones((10,10))
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

* For an integer $n$, create an array of length $3n$ filled with the cyclic pattern 1, 2, 3.  For example, for $n=2$, the output should be ```[1,2,3,1,2,3]```.

In [ ]:
n = 2
arr = np.arange(3*n) % 3 + 1
arr

array([1, 2, 3, 1, 2, 3])

### Slices

Describe the effect of each of the following slices in words.

The first set of slices refer to the following array:
```Python
a = np.arange(10)
```

For example, the slice ```a[0:5]``` yields the first five elements of the array.


In [40]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Slice 1:
```Python
a[::2]
```

In [41]:
a[::2]

array([0, 2, 4, 6, 8])

What this slice is doing is going through the whole array starting from 0 and incrementing my every other value in the original arrary

Slice 2:
```Python
a[5:]
```

In [42]:
a[5:]

array([5, 6, 7, 8, 9])

This returns all elements from index 5 till the end of the orginal array. 

The next set of questions refer to the following two-dimensional array, i.e. matrix:

```Python
a2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
```

In [44]:
a2d = np.array([[1,2, 3,], [4,5,6], [7,8,9]])
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Slice 3:
```Python
a2d[0]
```

In [45]:
a2d[0]

array([1, 2, 3])

*answer:  the first row of the matrix*

Slice 4:
```Python
a2d[1, :2]
```

In [46]:
a2d[1, :2]

array([4, 5])

the first two elements of the second row of a2d as in the column index it stops exclusively at index 2 in the column. 

Slice 5:
```Python
a2d[:, 1]
```

In [47]:
a2d[:,1]

array([2, 5, 8])

Returns all values in the index 1 column of the matrix or column 2. 

Slice 6:
```Python
a2d[:, 1:]
```

In [48]:
a2d[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

Takes all the rows starting form column index 1 or column 2 and the rest of columns left. 

Slice 7:
```Python
a2d[:,:]
```

In [49]:
a2d[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Displays all rows and columns of matrix

Here's a more challenging exercise that you can solve using slices:

* Create a 8x8 matrix that looks like this:

```
[[0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]]
```

Hint:  even and odd numbered rows each are filled with the same pattern.


In [ ]:
Mat2 = np.ones((8,8))

Mat2[::2, ::2] = 0 
Mat2[1::2, 1::2] = 0
Mat2 



array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])